version: '3.5'
# Use this script for running up nightfall_3 client in 'developer' mode with local
# bindings.  See the readme for more information.
services:
  client_1:
    image: ghcr.io/eyblockchain/nightfall3-client:latest
    volumes:
      - type: volume
        source: build_client_1
        target: /app/build
    networks:
      - nightfall_network
    ports:
      - 8090:80
    depends_on:
      - worker_1
      - mongodb_client_1
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-localhost}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      BLOCKCHAIN_WS_HOST: ${BLOCKCHAIN_WS_HOST:-blockchain}
      BLOCKCHAIN_PORT: ${BLOCKCHAIN_PORT:-8546}
      CIRCOM_WORKER_HOST: worker_1
      MONGO_URL: ${CLIENT_MONGO_URL:-mongodb://mongodb_client_1}
      CONTRACT_FILES_URL: ${CONTRACT_FILES_URL:-https://nightfallv3-proving-files-tmp-demo.s3.eu-central-1.amazonaws.com/build}
    command: ['npm', 'run', 'dev']

  mongodb_client_1:
    image: mongo:4.4.1-bionic
    hostname: mongodb_client_1
    ports:
      - 27018:27017
    networks:
      - nightfall_network
    command: --quiet
    volumes:
      - type: volume
        source: mongodb_client_1
        target: /data/db

  worker_1:
    image: ghcr.io/eyblockchain/nightfall3-worker:latest
    volumes:
      - type: volume
        source: proving_files_client_1
        target: /app/output/
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      CIRCUIT_FILES_URL: ${CIRCUIT_FILES_URL}

volumes:
  mongodb_client_1:
  proving_files_client_1:
  build_client_1:

networks:
  nightfall_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
